### ISSUE TITLE
Incorrect handling of sub-collections

### ISSUE THREAD

**Issue by stiiifff** [khalidsalomao/SimpleHelpers.Net#7]
Hi Khalid,

First of all, thanks for the very useful library, I'm using it in a client project. I haven't found another implementation that is as handy and low-ceremony as yours :+1: 
I just found a little issue in sub-collections, let me explain it.
If you have an original object:
`{
  "Children": [
    {
      "Name": "Alice"
    }
  ]
}`
and a modified one:
`{
  "Children": [
    {
      "Name": "Alice"
    },
    {
      "Name": "Bob"
    }
  ]
}`
If I do a GenerateDiff and then PatchObject one the original object, I get this:
`{
  "Children": [
   {"Name": "Alice"},
   null
  ]
}`

I have addressed the issue by making 2 small changes in the Patch method:
'return array' in the block that deals with arrays, 'return sourceObj' in the block that deals with objects, and remove the 'return sourceJson' at the end of the method. Problem is then fixed, and I think the code is a bit less confusing as well.

Attached is a small unit test that highlights the issue.
Would be awesome if you could integrate this fix, thx :)

[ObjectDiffPatchArrayIssue.zip](https://github.com/khalidsalomao/SimpleHelpers.Net/files/272919/ObjectDiffPatchArrayIssue.zip)

**Comment by khalidsalomao** [comment]
@stiiifff ,

Thanks for taking time to address the issue and prepare a fix with tests included! :smile:

Could you prepare a *Pull request* ? It would make the code review and integration a **lot** easier for me!

It is very simple:
1- create a fork
2- commit your changes
3- use github button *New pull request* 

Thanks!
Best!

**Comment by khalidsalomao** [comment]
@stiiifff I just updated Nuget.org with a version that should address this problem. Could you check it out?
I applied a patch that @kkostov submitted 5 months ago.
Best!

**Comment by stiiifff** [comment]
Thanks for taking the tim, I will check it out. Didn't have time to submit a PR but next time I'll do ;)
